# Site settings
title: OlivaSubHlp
author: 简律纯
email: HsiangNianian@outlook.com
description: thoughts? 
logo: https://academic.jyunko.cn/assets/retro.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hsiangnianian.github.io/OlivaSubHlp/" # the base hostname & protocol for your site

twitter: HsiangNianian
github: HsiangNianian
facebook: hsiang.nianian
soundcloud: hsiang_nianian
instagram: hsiang_nianian 

google_analytics: G-WQVB7M8ZZ2

disqus:
  shortname: cypress-github-io

show_excerpts: true

  
# Build settings
markdown: kramdown
theme: minima
# remote_theme: luoyan35714/LessOrMore
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
