name: CI
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACK_NAME: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pack
        run: |
          if [ ! $PACK_NAME ]; then
              PACK_NAME=${GITHUB_REPOSITORY##*/} 
          fi
          echo "PACK_NAME=$PACK_NAME" >> $GITHUB_ENV
          cd $PACK_NAME
          zip -r ../$PACK_NAME.opk ./
      
      - name: 读取当前版本号
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./${{ env.PACK_NAME }}/app.json
          property: version

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.PACK_NAME }}v${{steps.version.outputs.value}}
          path: ${{ env.PACK_NAME }}.opk
